Update mirror-bot.yml

diff --git a/.github/workflows/mirror-bot.yml b/.github/workflows/mirror-bot.yml
--- a/.github/workflows/mirror-bot.yml
+++ b/.github/workflows/mirror-bot.yml
@@ -1,4 +1,4 @@
-name: MirrorBot Environment
+name: Deploy
 
 on:
   push:
@@ -8,12 +8,13 @@ on:
    
 env:
   # Change these values if you have forked it for your own works
-  GitHubMail: rohanmourya43@gmail.com
-  GitHubName: NoOneCaresToMe
+  GitHubMail: "rohan.mourya43@gmail.com"
+  GitHubName: "NoOneCares" 
+  Branch: "master"
 
 jobs:
-  debug:
-    runs-on: ubuntu-20.04
+  build:
+    runs-on: ubuntu-latest
 
     steps:
       - name: Checkout
@@ -25,19 +26,27 @@ jobs:
           git config --global user.name ${GitHubName}
           git config --global credential.helper store
           echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
-      # Cleanup The Actions Workspace Using Custom Composite Run Actions free up space
-     # - uses: rokibhasansagar/slimhub_actions@main
+
+      # Cleanup The Actions Workspace Using Custom Composite Run Actions
+      - uses: rokibhasansagar/slimhub_actions@main
 
       - name: Clone The Secret Mirror Repository
         run: |
-          git clone https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.MIRROR_REPOSLUG }} source
-      - name: running Bot
+          git clone https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.MIRROR_REPOSLUG }} -b ${Branch} source
+
+      - name: Compile The Mirroring Docker Container
+        run: |
+          cd source || exit 1
+          docker container prune --force || true
+          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
+          docker image ls
+
+      - name: running Docker
         timeout-minutes: 340
         continue-on-error: true
         run: |
-          cd source
-          ./start.sh
-          npm start
+          docker run --privileged --rm -i mirror-bot
+
       - name: Loop Workflow
         continue-on-error: true
         run: |
@@ -46,5 +55,5 @@ jobs:
           cd loop || exit 1
           echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
           git add looper.txt
-          git commit --amend -m "Workflow : Loop at $(TZ='Asia/Kolkata' date +"%b %e, %l:%M %p")"
-          git push -qf https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
+          git commit -m "Workflow : Loop"
+          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
